version: 2.1
orbs:
  node: circleci/node@4.1.0
  sam: circleci/aws-sam-serverless@2.1.0
  s3: circleci/aws-s3@2.0.0

jobs:
  build-frontend:
    docker:
      - image: 'cimg/node:12.2'
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          cache-path: ~/project/frontend/node_modules
          override-ci-command: npm install
      - run: cd frontend && npm run build
      - persist_to_workspace:
          root: ~/project/frontend
          paths: [ build ]
  deploy-frontend:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - s3/sync:
          from: /tmp/workspace/build
          to: 's3://ebrouwer.dev-website'

  deploy-backend:
    working_directory: ~/project/backend
    executor:
      machine-image: 'ubuntu-2004:202010-01'
      name: default
    steps:
      - checkout
      - sam/install
      - sam/build:
          template: ./template.yaml
          use-container: false
      - sam/deploy:
          parameter-overrides: EtherscanApiKey=$ETHERSCAN_API_KEY
          s3-bucket: ebrouwer.dev-sam
          stack-name: ebrouwerdev-backend

workflows:
  deploy-backend:
    jobs:
      - deploy-backend:
          context: Personal AWS
  deploy-frontend:
    jobs:
      - build-frontend
      - deploy-frontend:
          context: Personal AWS
          requires: [ build-frontend ]
