version: 2.1
orbs:
  node: circleci/node@4.1.0
  sam: circleci/aws-sam-serverless@2.1.0
  s3: circleci/aws-s3@2.0.0
jobs:
  build-frontend:
    docker:
      - image: 'cimg/node:12.2'
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          cache-path: ~/project/frontend/node_modules
          override-ci-command: npm install
      - run: cd frontend && npm run build
      - run: mkdir /tmp && mv frontend/build /tmp/build
      - save_cache:
          key: react-package
          paths:
            - /tmp/build
  deploy-frontend:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - restore_cache:
          key: react-package
      - s3/sync:
          from: /tmp/build
          to: 's3://ebrouwer.dev-website'
workflows:
  deploy-backend:
    jobs:
      - sam/deploy:
          context: Personal AWS
          name: sam-deploy
          stack-name: ebrouwerdev-backend
          template: ./backend/template.yaml
          s3-bucket: ebrouwer.dev-sam
  deploy-frontend:
    jobs:
      - build-frontend
      - deploy-frontend:
          context: Personal AWS
          requires:
            - build-frontend
