name: Fly Deploy
on:
  push:
    branches:
      - remix
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_SECRET_API_KEY: ${{ secrets.PORKBUN_SECRET_API_KEY }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set GCP_CREDENTIALS="${GCP_CREDENTIALS}" \
                             GCP_PROJECT_ID="${GCP_PROJECT_ID}" \
                             SESSION_SECRET="${SESSION_SECRET}" \
                             ENCRYPTION_SECRET="${ENCRYPTION_SECRET}" \
                             RESEND_API_KEY="${RESEND_API_KEY}" \
                             PORKBUN_API_KEY="${PORKBUN_API_KEY}" \
                             PORKBUN_SECRET_API_KEY="${PORKBUN_SECRET_API_KEY}" \
                             GCP_ZONE="us-central1-a"
      - run: flyctl deploy --remote-only
