name: Fly Deploy
on:
  push:
    branches:
      - remix
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set GCP_CREDENTIALS="${GCP_CREDENTIALS}"
      - run: flyctl secrets set GCP_PROJECT_ID="${GCP_PROJECT_ID}"
      - run: flyctl secrets set SESSION_SECRET="${SESSION_SECRET}"
      - run: flyctl secrets set ENCRYPTION_SECRET="${ENCRYPTION_SECRET}"
      - run: flyctl secrets set RESEND_API_KEY="${RESEND_API_KEY}"
      - run: flyctl deploy --remote-only
